<?php use Fisharebest\Webtrees\Auth; ?>
<?php use Fisharebest\Webtrees\Functions\FunctionsPrint; ?>
<?php use Fisharebest\Webtrees\I18N; ?>
<?php use Fisharebest\Webtrees\View; ?>

<?php if ($individual->isPendingDeletion()) : ?>
    <?php if (Auth::isModerator($individual->tree())) : ?>
        <?= view('components/alert-warning-dismissible', [
            'alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */
                I18N::translate('This individual has been deleted. You should review the deletion and then %1$s or %2$s it.', '<a href="#" class="alert-link" onclick="accept_changes(\'' . e($individual->xref()) . '\', \'' . e($individual->tree()->name()) . '\');">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'accept') . '</a>', '<a href="#" class="alert-link" onclick="reject_changes(\'' . e($individual->xref()) . '\', \'' . e($individual->tree()->name()) . '\');">' . I18N::translateContext('You should review the deletion and then accept or reject it.', 'reject') . '</a>') . ' ' . FunctionsPrint::helpLink('pending_changes'),
        ]) ?>
    <?php elseif (Auth::isEditor($individual->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This individual has been deleted. The deletion will need to be reviewed by a moderator.') . ' ' . FunctionsPrint::helpLink('pending_changes')]) ?>
    <?php endif ?>
<?php elseif ($individual->isPendingAddition()) : ?>
    <?php if (Auth::isModerator($individual->tree())) : ?>
        <?= view('components/alert-warning-dismissible', [
            'alert' => /* I18N: %1$s is “accept”, %2$s is “reject”. These are links. */
                I18N::translate('This individual has been edited. You should review the changes and then %1$s or %2$s them.', '<a href="#" class="alert-link" onclick="accept_changes(\'' . e($individual->xref()) . '\', \'' . e($individual->tree()->name()) . '\');">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'accept') . '</a>', '<a href="#" class="alert-link" onclick="reject_changes(\'' . e($individual->xref()) . '\', \'' . e($individual->tree()->name()) . '\');">' . I18N::translateContext('You should review the changes and then accept or reject them.', 'reject') . '</a>') . ' ' . FunctionsPrint::helpLink('pending_changes'),
        ]) ?>
    <?php elseif (Auth::isEditor($individual->tree())) : ?>
        <?= view('components/alert-warning-dismissible', ['alert' => I18N::translate('This individual has been edited. The changes need to be reviewed by a moderator.') . ' ' . FunctionsPrint::helpLink('pending_changes')]) ?>
    <?php endif ?>
<?php endif ?>

<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $individual->fullName() ?><?= $user_link ?>
        
        <?php
        //[RC] adjusted replaces $sex_records which are generated via IndividualController.formatSexRecord
        foreach ($individual->facts(['SEX']) as $n => $fact) {
            $individual = $fact->record();

            switch ($fact->value()) {
                case 'M':
                    $sex = I18N::translate('Male');
                    $container_class = 'male_gender';
                    $icon = view('icons/sex-M');
                    break;
                case 'F':
                    $sex = I18N::translate('Female');
                    $container_class = 'female_gender';
                    $icon = view('icons/sex-F');
                    break;
                default:
                    $sex = I18N::translateContext('unknown gender', 'Unknown');
                    $container_class = 'unknown_gender';
                    $icon = view('icons/sex-U');
                    break;
            }

            //$container_class = 'card';
            if ($fact->isPendingDeletion()) {
                $container_class .= ' wt-old';
            } elseif ($fact->isPendingAddition()) {
                $container_class .= ' wt-new';
            }

            if ($individual->canEdit()) {
                $edit_links = '<a class="btn btn-link" href="' . e(route('edit-fact', ['xref' => $individual->xref(), 'fact_id' => $fact->id(), 'ged' => $individual->tree()->name()])) . '" title="' . I18N::translate('Edit the gender') . '">' . view('icons/edit') . '<span class="sr-only">' . I18N::translate('Edit the gender') . '</span></a>';
            } else {
                $edit_links = '';
            }

            /*
            echo '
              <div class="' . $container_class . '">
                <div class="card-header" role="tab" id="name-header-add">
                  <div class="card-title mb-0">
                    <b>' . I18N::translate('Gender') . '</b> ' . $sex . $edit_links . '
                  </div>
                </div>
              </div>';
            */
          
            echo '<span class="vt_gender '.$container_class.'" title="'.$sex.'">'.$icon.$edit_links.'</span>,';
          }        
        ?>
        
        <?= $individual->getLifeSpan() ?> <?= $age ?>
    </h2>
    <?php if ($individual->canEdit()) : ?>
        <?= view('individual-page-menu', ['individual' => $individual, 'count_names' => $count_names, 'count_sex' => $count_sex]) ?>
    <?php endif ?>
</div>

<div class="row">
    <?php
    //[RC] adjusted from
    //'col-sm-12' : 'col-sm-8'
    ?>
    <div class="<?= $sidebars->isEmpty() ? 'col-sm-12' : 'col-sm-9' ?>">
        <div class="row mb-4">
            <!-- Individual images -->
            <?php
            //[RC] adjusted from
            //<div class="col-sm-3">
            ?>
            <div class="col-sm-2">
                <?php if (empty($individual_media)) : ?>
                    <i class="wt-individual-silhouette wt-individual-silhouette-<?= strtolower($individual->sex()) ?>"></i>
                <?php elseif (count($individual_media) === 1) : ?>
                    <?= $individual_media[0]->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>
                <?php else : ?>
                    <div id="individual-images" class="carousel slide" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">
                            <?php foreach ($individual_media as $n => $media_file) : ?>
                                <div class="carousel-item <?= $n === 0 ? 'active' : '' ?>">
                                    <?= $media_file->displayImage(200, 260, 'crop', ['class' => 'img-thumbnail img-fluid w-100']) ?>
                                </div>
                            <?php endforeach ?>
                        </div>
                        <a class="carousel-control-prev" href="#individual-images" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only"><?= I18N::translate('previous') ?></span>
                        </a>
                        <a class="carousel-control-next" href="#individual-images" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only"><?= I18N::translate('next') ?></span>
                        </a>
                    </div>

                <?php endif ?>

                <?php
                //[RC] adjusted - why are these even here and not on the Media tab??
                //for now moved, into the edit menu
                ?>
                <?php if (false) /*(Auth::isEditor($individual->tree()))*/ : ?>
                    <?php if ($individual->facts(['OBJE'])->count() > 1) : ?>
                        <div>
                            <a href="<?= e(route('reorder-media', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref()])) ?>">
                                <?= view('icons/reorder') ?>
                                <?= I18N::translate('Re-order media') ?>
                            </a>
                        </div>
                    <?php endif ?>

                    <?php if ($individual->tree()->getPreference('MEDIA_UPLOAD') >= Auth::accessLevel($individual->tree())) : ?>
                        <div>
                            <a href="<?= e(route('add-fact', ['ged' => $individual->tree()->name(), 'xref' => $individual->xref(), 'fact' => 'OBJE'])) ?>">
                                <?= I18N::translate('Add a media object') ?>
                            </a>
                        </div>
                    <?php endif ?>
                <?php endif ?>
            </div>

            <!-- Name accordion -->
            <?php
            //[RC] adjusted from
            //<div class="col-sm-9">
            ?>
            <div class="col-sm-10" id="individual-names" role="tablist">
                <?php foreach ($name_records as $name_record) : ?>
                    <?= $name_record ?>
                <?php endforeach ?>
                
                <!-- [RC] moved elsewhere
                <?php foreach ($sex_records as $sex_record) : ?>
                    <?= $sex_record ?>
                <?php endforeach ?>
                -->
            </div>
        </div>

        <div class="wt-tabs-individual" id="individual-tabs">
            <ul class="nav nav-tabs flex-wrap">
                <?php foreach ($tabs as $tab) : ?>
                    <li class="nav-item">
                        <a class="nav-link<?= $tab->isGrayedOut($individual) ? ' text-muted' : '' ?>" data-toggle="tab" role="tab" data-href="<?= e(route('individual-tab', ['xref' => $individual->xref(), 'ged' => $individual->tree()->name(), 'module' => $tab->name()])) ?>" href="#<?= $tab->name() ?>">
                            <?= $tab->tabTitle() ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($tabs as $tab) : ?>
                    <div id="<?= $tab->name() ?>" class="tab-pane fade wt-ajax-load" role="tabpanel"><?php if (!$tab->canLoadAjax()) :
                        ?><?= $tab->getTabContent($individual) ?><?php
                             endif ?></div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
    <?php if ($sidebars->isNotEmpty()) : ?>
    <?php
    //[RC] adjusted from
    //<div class="col-sm-4"
    ?>
    <div class="col-sm-3" id="sidebar" role="tablist">
        <?php foreach ($sidebars as $sidebar) : ?>
            <div class="card">
                <div class="card-header" role="tab" id="sidebar-header-<?= $sidebar->name() ?>">
                    <div class="card-title mb-0">
                        <a data-toggle="collapse" data-parent="#sidebar" href="#sidebar-content-<?= $sidebar->name() ?>" aria-expanded="<?= $sidebar->name() === 'family_nav' ? 'true' : 'false' ?>" aria-controls="sidebar-content-<?= $sidebar->name() ?>">
                            <?= $sidebar->sidebarTitle() ?>
                        </a>
                    </div>
                </div>
                <div id="sidebar-content-<?= $sidebar->name() ?>" class="collapse<?= $sidebar->name() === 'family_nav' ? ' show' : '' ?>" role="tabpanel" aria-labelledby="sidebar-header-<?= $sidebar->name() ?>">
                    <div class="card-body">
                        <?= $sidebar->getSidebarContent($individual) ?></div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
    <?php endif ?>
</div>

<?php View::push('javascript') ?>
<script>
  "use strict";

  // Bootstrap tabs - load content dynamically using AJAX
  $('a[data-toggle="tab"][data-href]').on('show.bs.tab', function () {
    $(this.getAttribute('href') + ':empty').load($(this).data('href'));
  });

  // If the URL contains a fragment, then activate the corresponding tab.
  // Use a prefix on the fragment, to prevent scrolling to the element.
  var target = window.location.hash.replace("tab-", "");
  var tab    = $("#individual-tabs .nav-link[href='" + target + "']");
  // If not, then activate the first tab.
  if (tab.length === 0) {
    tab = $("#individual-tabs .nav-link:first");
  }
  tab.tab("show");

  // If the user selects a tab, update the URL to reflect this
  $('#individual-tabs a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    window.location.hash = "tab-" + e.target.href.substring(e.target.href.indexOf('#') + 1);
  });
</script>
<?php View::endpush() ?>

<?= view('modals/ajax') ?>
