<?php

use Fisharebest\Webtrees\I18N;
use Vesta\CommonI18N;

//original view (easier to monkeypatch than to extend properly)
ob_start();
echo view('::admin/tags', [
            'all_family_tags'        => $all_family_tags,
            'all_individual_tags'    => $all_individual_tags,
            'custom_family_tags'     => $custom_family_tags,
            'custom_gedcom_l_tags'   => $custom_gedcom_l_tags,
            'custom_individual_tags' => $custom_individual_tags,
            'custom_fam_fact'        => $custom_fam_fact,
            'custom_fam_nchi'        => $custom_fam_nchi,
            'custom_resi_value'      => $custom_resi_value,
            'custom_time_tags'       => $custom_time_tags,
            'element_factory'        => $element_factory,
            'title'                  => $title,
        ]);

$parentHtml = ob_get_clean();

$search = "<h1>" . $title . "</h1>";

$link = '<a href="https://github.com/vesta-webtrees-2-custom-modules/vesta_common/blob/master/docs/GEDCOMTags.md">'.I18N::translate('here').'</a>';

$ext = I18N::translate(
    'Note that in addition to the configuration options below, %1$s allows you to configure the visibility of each specific tag in detail, as described %2$s.',
    CommonI18N::titleVestaCLAF(),
    $link);

$adjustedHtml = str_replace($search, $search . $ext, $parentHtml);

echo $adjustedHtml;

?>
