<?php

use Cissee\WebtreesExt\Services\GedcomEditServiceExt2;
use Fisharebest\Webtrees\I18N;

$gedcom_edit_service = new GedcomEditServiceExt2();
$override = $gedcom_edit_service->getPreference($tree, $tag);

$options = [];
$options[''] = I18N::translate('no adjustment (use setting for all events as shown below)');
$options['LEVEL0'] = I18N::translate('hide always');
$options['LEVEL1'] = I18N::translate('hide in multi-fact dialogs, show otherwise');
if ($indent) {
    $options['LEVEL1a'] = I18N::translate('hide in multi-fact dialogs, show and expand subtags otherwise');
}
$options['LEVEL2'] = I18N::translate('show always');
if ($indent) {
    $options['LEVEL2a'] = I18N::translate('show and expand subtags always');
}

?>

<div class="form-group">
    <?= view('components/radios', [
        'name' => 'CONFIG_GEDCOM_FIELDS',
        'options' => $options,
        'selected' => $override]) ?>
</div>
