<?php

use Cissee\WebtreesExt\Services\GedcomEditServiceExt2;
use Fisharebest\Webtrees\I18N;

$gedcom_edit_service = new GedcomEditServiceExt2();
$override = $gedcom_edit_service->getPreference($tree, $tag);

$options = [];
$options[''] = I18N::translate('no adjustment');
$options['LEVEL0'] = I18N::translate('hide always');
$options['LEVEL1'] = I18N::translate('hide for new individuals, show otherwise');
if ($indent) {
    $options['LEVEL1a'] = I18N::translate('hide for new individuals, show and expand subtags otherwise');
}
$options['LEVEL2'] = I18N::translate('show always');
if ($indent) {
    $options['LEVEL2a'] = I18N::translate('show and expand subtags always');
}

$tag2parts = explode(':',$tag);
$tagHead = array_shift($tag2parts);
array_shift($tag2parts);
$tagRemaining = implode(':',$tag2parts);

?>

<div class="form-group">
    <?= I18N::translate('Apply the following setting to \'%1$s\' within all \'%2$s\' events, unless the event is configured explicitly:', $tagRemaining, $tagHead) ?>
    
    <?= view('components/radios', [
        'name' => 'CONFIG_GEDCOM_FIELDS_2', 
        'options' => $options, 
        'selected' => $override]) ?>
</div>

