<?php

use Cissee\WebtreesExt\Services\GedcomEditServiceExt2;
use Fisharebest\Webtrees\Services\GedcomEditService;
use Fisharebest\Webtrees\Tree;

/**
 * @var string            $cancel_url
 * @var GedcomEditService $gedcom_edit_service
 * @var string            $post_url
 * @var string            $title
 * @var Tree              $tree
 * @var string            $url
 */

//[RC adjusted]
$gedcom_edit_service = new GedcomEditServiceExt2(true);

//call original view
echo view('::edit/new-individual', [
    'cancel_url'          => $cancel_url,
    'facts'               => $facts,
    'gedcom_edit_service' => $gedcom_edit_service,
    'post_url'            => $post_url,
    'title'               => $title,
    'tree'                => $tree,
    'url'                 => $url,
]);

