<?php

use Fisharebest\Webtrees\DebugBar;
use Fisharebest\Webtrees\FlashMessages;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Module\ModuleGlobalInterface;
use Fisharebest\Webtrees\Module\ModuleThemeInterface;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Webtrees;
use Psr\Http\Message\ServerRequestInterface;

//[RC] adaptd from layouts/default

/**
 * @var string $title
 * @var string $content
 */

?>

<!DOCTYPE html>
<html dir="<?= I18N::locale()->direction() ?>" lang="<?= I18N::locale()->languageTag() ?>">
    <head>
        <meta charset="UTF-8">
        <meta name="csrf" content="<?= e(csrf_token()) ?>">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="<?= e($meta_robots ?? 'noindex') ?>">
        <meta name="generator" content="<?= e(Webtrees::NAME) ?> <?= e(Webtrees::VERSION) ?>">
        <meta name="description" content="<?= $meta_description ?? '' ?>">

        <title>
            <?= strip_tags($title) ?>
            <?php if ($tree !== null && $tree->getPreference('META_TITLE') !== '') : ?>
                – <?= e($tree->getPreference('META_TITLE')) ?>
            <?php endif ?>
        </title>

        <!--Generic favicons-->
        <link rel="icon" sizes="32x32" href="<?= e(asset('favicon-32.png')) ?>">
        <link rel="icon" sizes="128x128" href="<?= e(asset('favicon-128.png')) ?>">
        <link rel="icon" sizes="192x192" href="<?= e(asset('favicon-192.png')) ?>">
        <!--Android-->
        <link rel="shortcut icon" sizes="196x196" href="<?= e(asset('favicon-196.png')) ?>">
        <!--iPad-->
        <link rel="apple-touch-icon" sizes="152x152" href="<?= e(asset('favicon-152.png')) ?>">
        <!--iPhone-->
        <link rel="apple-touch-icon" sizes="180x180" href="<?= e(asset('favicon-180.png')) ?>">
        <!--IE11/Edge-->
        <meta name="msapplication-config" content="<?= e(asset('browserconfig.xml')) ?>">

        <link rel="manifest" href="<?= e(asset('site.webmanifest')) ?>">

        <link rel="stylesheet" href="<?= e(asset('css/vendor.min.css')) ?>">
        <?php foreach (app(ModuleThemeInterface::class)->stylesheets() as $stylesheet) : ?>
            <link rel="stylesheet" href="<?= e($stylesheet) ?>">
        <?php endforeach ?>

        <?= View::stack('styles') ?>

        <?= app(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module->headContent();
        })->implode('') ?>

        <?= DebugBar::renderHead() ?>
    </head>

    <body class="wt-global wt-theme-<?= e(app(ModuleThemeInterface::class)->name()) ?> wt-route-<?= e(app(ServerRequestInterface::class)->getAttribute('route')->name) ?>">

        <main id="content" class="wt-main-wrapper">
            <div class="container wt-main-container">
                <div class="flash-messages">
                    <?php foreach (FlashMessages::getMessages() as $message) : ?>
                        <div class="alert alert-<?= e($message->status) ?> alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="<?= I18N::translate('close') ?>">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <?= $message->text ?>
                        </div>
                    <?php endforeach ?>
                </div>

                <?= $content ?>
            </div>
        </main>

        <script src="<?= e(asset('js/vendor.min.js')) ?>"></script>
        <script src="<?= e(asset('js/webtrees.min.js')) ?>"></script>

        <script>
            // Trigger an event when we click on an (any) image
            $('body').on('click', 'a.gallery', function () {
                // Enable colorbox for images
                $("a[type^=image].gallery").colorbox({
                    // Don't scroll window with document
                    fixed:          true,
                    width:          "85%",
                    height:         "85%",
                    current:        "",
                    previous:       '<i class="fas fa-arrow-left wt-icon-flip-rtl" title="<?= I18N::translate('previous') ?>"></i>',
                    next:           '<i class="fas fa-arrow-right wt-icon-flip-rtl" title="<?= I18N::translate('next') ?>"></i>',
                    slideshowStart: '<i class="fas fa-play" title="<?= I18N::translate('Play') ?>"></i>',
                    slideshowStop:  '<i class="fas fa-stop" title="<?= I18N::translate('Stop') ?>"></i>',
                    close:          '<i class="fas fa-times" title="<?= I18N::translate('close') ?>"></i>',
                    title:          function () {
                        return this.dataset.title;
                    },
                    photo:          true,
                    rel:            "gallery", // Turn all images on the page into a slideshow
                    slideshow:      true,
                    slideshowAuto:  false,
                    // Add wheelzoom to the displayed image
                    onComplete:     function () {
                        // Disable click on image triggering next image
                        // https://github.com/jackmoore/colorbox/issues/668
                        $(".cboxPhoto").unbind("click");

                        wheelzoom(document.querySelectorAll(".cboxPhoto"));
                    }
                });
            });
        </script>

        <?= View::stack('javascript') ?>

        <?= app(ModuleService::class)->findByInterface(ModuleGlobalInterface::class)->map(static function (ModuleGlobalInterface $module): string {
    return $module->bodyContent();
        })->implode('') ?>

        <?= DebugBar::render() ?>
    </body>
</html>
